[tool.poetry]
name = "langchain-layer"
version = "2.0.0"
authors = [ "Amazon Web Services" ]
description = "Layer for LangChain libraries"
packages = [
    { include = "*.toml" },
    { include = "*.lock" },
]

[tool.poetry.dependencies]
python = "^3.11"
numpy = "1.26.4"
langchain = "0.2.11"
langchain-core = "0.2.25"
langchain-aws = "0.1.12"

[build-system]
requires = [ "poetry-core>=1.9.0" ]
build-backend = "poetry.core.masonry.api"