[tool.poetry]
name = "langchain-layer"
version = "1.4.2"
authors = [ "Amazon Web Services" ]
description = "Layer for LangChain libraries"
packages = [
    { include = "*.toml" },
    { include = "*.lock" },
]

[tool.poetry.dependencies]
python = "^3.11"
numpy = "1.26.4"
langchain = "0.1.19"
langchain-core = "0.1.52"
langchain-community = "0.0.38"
langchain-aws = "0.1.3"


[build-system]
requires = [ "poetry-core>=1.0.8" ]
build-backend = "poetry.core.masonry.api"