[tool.poetry]
name = "boto3-layer"
version = "2.0.1"
authors = [ "Amazon Web Services" ]
description = "Layer for AWS Boto3 python SDK"
packages = [
    { include = "*.toml" },
    { include = "*.lock" },
]

[tool.poetry.dependencies]
botocore = "1.34.151"
boto3 = "1.34.151"
python = "^3.11"

[build-system]
requires = [ "poetry-core>=1.9.0" ]
build-backend = "poetry.core.masonry.api"